# Generated by Django 3.1.4 on 2021-07-01 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': '权限'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '角色'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户'},
        ),
    ]
