# Generated by Django 3.1.4 on 2021-07-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_rbac', '0002_auto_20210701_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='icon',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='菜单图标'),
        ),
        migrations.AddField(
            model_name='permission',
            name='isMenu',
            field=models.BooleanField(default=False, verbose_name='是否可以做菜单'),
        ),
    ]
