# Generated by Django 3.1.4 on 2021-07-01 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_rbac', '0003_auto_20210702_0036'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='permission',
            table='permission',
        ),
        migrations.AlterModelTable(
            name='role',
            table='role',
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='userinfo',
        ),
    ]
