# Generated by Django 3.1.4 on 2021-07-02 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_rbac', '0004_auto_20210702_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='一级菜单')),
                ('icon', models.CharField(blank=True, max_length=32, null=True, verbose_name='菜单图标')),
            ],
            options={
                'verbose_name': '菜单',
                'db_table': 'menu',
            },
        ),
        migrations.RemoveField(
            model_name='permission',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='isMenu',
        ),
        migrations.AddField(
            model_name='permission',
            name='menu',
            field=models.ForeignKey(blank=True, help_text='null表示不是菜单,这个字段有值才表示二级菜单', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App_rbac.menu', verbose_name='所属菜单'),
        ),
    ]
