# Generated by Django 3.1.4 on 2021-07-02 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_rbac', '0005_auto_20210702_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='pid',
            field=models.ForeignKey(blank=True, help_text='对于非菜单权限需要选择一个可以成为菜单的权限,用户做默认展开和选中的菜单', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parents', to='App_rbac.permission', verbose_name='关联某个权限'),
        ),
    ]
