# Generated by Django 3.1.4 on 2021-07-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_rbac', '0006_permission_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='URL别名'),
        ),
    ]
