# Generated by Django 3.1.4 on 2021-07-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_rbac', '0007_permission_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='URL别名'),
        ),
    ]
