# Generated by Django 3.1.4 on 2021-07-26 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_web', '0002_auto_20210702_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_web.customer', verbose_name='关联客户'),
        ),
    ]
